# Cancel Order

# Identifier for who is requesting the service
uint16 requester_id

# generated order ID
string order_id

---

# Confirmation that this service call is processed
bool success

# This will provide a verbose message regarding order cancellation
string message