# Print Order for Packaging Machine

# A unique ID for this request
uint32 order_id

# Identifier for who is requesting the service
uint16 requester_id

# The unique ID of the pillbox ID
uint32 dosette_box_id

---

# Confirmation that this service call is processed
bool success

# The unique ID of the pillbox ID
DailyPackageInfo[7] pkgs_info

# This will provide a verbose message regarding order submission
string message
